apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Chart.Name }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: {{ .Chart.Name }}
    creationPolicy: Owner
  data:
  - secretKey: cloudflare-api-token
    remoteRef:
      key: infra-secrets
      property: cloudflare-api-token