{{ range .Values.secretStore }}
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-token
  namespace: {{ $.Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: external-secrets
{{- if .labels }}
  labels: {{ toYaml .labels | nindent 4 }}
{{- end }}
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ $.Release.Name }}
  namespace: {{ $.Release.Namespace }}
{{- end -}}
