clusterissuer:
  name: letsencrypt
  email: chelbsik@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cert-manager
            key: cloudflare-api-token
      selector:
        dnsZones:
        - 'kirillplis.uk'

cert-manager:
  enabled: true
  installCRDs: true
  ingressShim:
    defaultIssuerName: "letsencrypt"
    defaultIssuerKind: "ClusterIssuer"

  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::211125442702:role/cert-manager"

  securityContext:
    fsGroup: 1001
    runAsUser: 1001