apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-ssh-creds
  argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: argocd-repo-creds-ssh-creds
    creationPolicy: Owner
  data:
  - secretKey: sshPrivateKey
    remoteRef:
      key: infra-secrets
      property: argocd-ssh-private-key
  - secretKey: url
    remoteRef:
      key: infra-secrets
      property: argocd-ssh-url
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
  - secretKey: admin.password
    remoteRef:
      key: infra-secrets
      property: argocd-admin-password
  - secretKey: admin.passwordMtime
    remoteRef:
      key: infra-secrets
      property: argocd-admin-password-time
  - secretKey: server.secretkey
    remoteRef:
      key: infra-secrets
      property: argocd-server-secretkey