apiVersion: v2
name: external-secrets
description: A Helm chart for external secrets
type: application
version: 0.1.0
appVersion: "v0.9.13"
dependencies:
  - name: external-secrets
    version: 0.9.13
    repository: https://charts.external-secrets.io