apiVersion: v2
name: argocd
description: A Helm chart for apps to be delivered by Argo CD to Kubernetes
type: application
version: 1.0.0
appVersion: 2.10.3
dependencies:
  - name: argo-cd
    version: 6.7.3
    repository: https://argoproj.github.io/argo-helm