{{- range $appName, $appConfig := .Values.apps }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Chart.Name }}-{{ $appName }}
spec:
  maxReplicas: {{ $appConfig.hpa.maxReplicas }}
  minReplicas: {{ $appConfig.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Chart.Name }}-{{ $appName }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $appConfig.hpa.cpuTarget }}
---
{{- end }}