name: Build greet-api

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - greet-api/*
    

env:
  AWS_ACCOUNT_ID: 211125442702
  AWS_ROLE_NAME: GithubActionsRole
  AWS_REGION: eu-central-1
  REGISTRY_URL: 211125442702.dkr.ecr.eu-central-1.amazonaws.com
  DOCKERFILE_PATH: ./greet-api
  DOCKERFILE_NAME: Dockerfile
  APPLICATION_NAME: greet-api
  INFRA_REPO: kirillplis/parcellab-sre-challenge
  INFRA_REPO_BRANCH: main
  HELM_CHART_PATH: kubernetes/helm/apps

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push container image
        working-directory: ${{ env.DOCKERFILE_PATH }}
        run: |
          docker build . -f ${{ env.DOCKERFILE_NAME }} \
            -t ${{ env.REGISTRY_URL }}/${{ env.APPLICATION_NAME }}:$GITHUB_SHA
          docker push -a ${{ env.REGISTRY_URL }}/${{ env.APPLICATION_NAME }}
  argocd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out application code
        uses: actions/checkout@v3

      - name: Git Commit - get commit author data
        run: |-
          echo "COMMIT_AUTHOR_NAME=$(git log --format='%an <%ae>' -n 1 HEAD | cut -d '<' -f 2 | cut -d '@' -f 1)" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR_EMAIL=$(git log --format='%an <%ae>' -n 1 HEAD | cut -d '<' -f 2 | cut -d '>' -f 1)" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$(git log --format='%an <%ae>' -n 1 HEAD)" >> $GITHUB_ENV
      
      - name: Infrastructure repo checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ env.INFRA_REPO }}
          ssh-key: ${{ secrets.INFRA_SSH_KEY }}
          ref: ${{ env.INFRA_REPO_BRANCH }}

      - name: Set new tags
        run: |
           yq -i ".image.tag = \"$GITHUB_SHA\"" ${{ env.HELM_CHART_PATH }}/${{ env.APPLICATION_NAME }}/values.yaml

      - name: Set new tags
        shell: bash
        run: |-
          git config user.name ${{ env.COMMIT_AUTHOR_NAME }}  
          git config user.email ${{ env.COMMIT_AUTHOR_EMAIL }}
          git add ${{ env.HELM_CHART_PATH }}/${{ env.APPLICATION_NAME }}/values.yaml
          git commit -m "Deploying image ${{ env.REGISTRY_URL }}/${{ env.APPLICATION_NAME }}:$GITHUB_SHA
          Author: ${{ env.COMMIT_AUTHOR }}"
          git push origin ${{ env.INFRA_REPO_BRANCH }}